-- CÂU 1
DROP TRIGGER IF EXISTS TRIG_INSER_GR;
DELIMITER $$
 CREATE TRIGGER TRIG_INSER_GR
 BEFORE INSERT ON `Group`
 FOR EACH ROW
BEGIN
	IF (NEW.CreateDate <= DATE_SUB(NOW(), interval 1 year)) THEN
	SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = 'KHÔNG THỂ TẠO GR';
	END IF;
END$$
 DELIMITER ;
INSERT INTO `Group`(GroupName,CreatorID,CreateDate)
VALUES ('100', '10', '2020-11-09');

-- CÂU 2
DROP TRIGGER IF EXISTS TRIG_INSER_SALE;
DELIMITER $$
 CREATE TRIGGER TRIG_INSER_SALE
 BEFORE INSERT ON `Account`
 FOR EACH ROW
BEGIN
	DECLARE dep_ID TINYINT;
	SELECT D.DepartmentID INTO dep_ID FROM `Department` D WHERE D.DepartmentName = 'Sale';
	IF (NEW.DepartmentID = dep_ID) THEN
	SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = '"Department "Sale" cannot add more user"';
	END IF;
END$$
 DELIMITER ;
INSERT INTO `Account`(Email,Username,FullName,DepartmentID,PositionID,CreateDate)
VALUES ('tavanmanh@gmail.com', 'fleta_rutherford1', 'NGYỄN VĂN A', '1', '2','2001-11-09');

-- CÂU 3
DROP TRIGGER IF EXISTS TRIG_GR;
DELIMITER $$
 CREATE TRIGGER TRIG_GR
 BEFORE INSERT ON `GroupAccount`
 FOR EACH ROW
BEGIN
	DECLARE GR_ID TINYINT;
	SELECT COUNT(GR.GroupID) INTO GR_ID FROM `GroupAccount` GR WHERE GR.GroupID = NEW.GroupID;
	IF (GR_ID >= 5) THEN
	SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = 'ĐÃ ĐỦ 5 THÀNH VIÊN';
	END IF;
END$$
 DELIMITER ;

-- CÂU 4
DROP TRIGGER IF EXISTS TRIG_QUES;
DELIMITER $$
 CREATE TRIGGER TRIG_QUES
 BEFORE INSERT ON `ExamQuestion`
 FOR EACH ROW
BEGIN
	DECLARE EX_QUES TINYINT;
	SELECT COUNT(EX.ExamID) INTO EX_QUES FROM `ExamQuestion` EX WHERE EX.ExamID = NEW.ExamID;
	IF (EX_QUES >= 10) THEN
	SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = 'ĐÃ ĐỦ 10 CÂU HỎI';
	END IF;
END$$
 DELIMITER ;
 
 -- CÂU 5
 DROP TRIGGER IF EXISTS TRIG_DLT_ADMIN;
DELIMITER $$
 CREATE TRIGGER TRIG_DLT_ADMIN
 BEFORE DELETE ON `Account`
 FOR EACH ROW
BEGIN
	DECLARE EMAIL_ADMIN VARCHAR(50);
	SET EMAIL_ADMIN = 'admin@gmail.com';
	IF (OLD.Email = EMAIL_ADMIN) THEN
    SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = 'ĐÂY LÀ TK ADMIN KHÔNG ĐƯỢC XÓA';
	END IF;
END$$
 DELIMITER ;
 DELETE FROM account A WHERE A.Email = 'admin@gmail.com';
 
 -- CÂU 6
 DROP TRIGGER IF EXISTS TRIG_INSER_WAITING;
DELIMITER $$
CREATE TRIGGER TRIG_INSER_WAITING
BEFORE INSERT ON `Account`
FOR EACH ROW
BEGIN
	DECLARE DEP_ID_WAITING TINYINT;
	SELECT D.DepartmentID INTO DEP_ID_WAITING FROM `Department` D WHERE D.DepartmentName = 'CHỜ VIỆC';
	IF (NEW.DepartmentID IS NULL) THEN
	SET NEW.DepartmentID=DEP_ID_WAITING;
	END IF;
END$$
 DELIMITER ;
 INSERT INTO `Account`(Email,Username,FullName,PositionID,CreateDate)
VALUES ('1','1', '1', '1','2001-11-09');

 -- CÂU 8
DELIMITER $$
CREATE TRIGGER TRIG_GENDER
BEFORE INSERT ON `Account`
FOR EACH ROW
	BEGIN
		IF NEW.Gender = 'Nam' THEN
			SET NEW.Gender = 'M';
		ELSEIF NEW.Gender = 'Nu' THEN
			SET NEW.Gender = 'F';
		ELSEIF NEW.Gender = 'Chưa xác định' THEN
			SET NEW.Gender = 'U';
		END IF ;
	END $$
DELIMITER ;

 INSERT INTO `Account`(Email,Gender,Username,FullName,PositionID,CreateDate,DepartmentID)
VALUES ('2','Nam','2', '2', '2','2001-11-09',2);

 -- CÂU 9
DROP TRIGGER IF EXISTS TRIG_DLT_EXAM;
DELIMITER $$
CREATE TRIGGER TRIG_DLT_EXAM
BEFORE DELETE ON `Exam`
FOR EACH ROW
BEGIN
	DECLARE CR_DATE DATETIME;
	SET CR_DATE = DATE_SUB(NOW(),INTERVAL 2 DAY);
	IF (OLD.CreateDate > CR_DATE) THEN
	SIGNAL SQLSTATE '12345'
	SET MESSAGE_TEXT = 'KHÔNG THỂ XÓA';
	END IF ;
END $$
DELIMITER ;
DELETE FROM exam E WHERE E.ExamID =1;

 -- CÂU 10
DROP TRIGGER IF EXISTS TRIG_DL;
DELIMITER $$
CREATE TRIGGER TRIG_DL
BEFORE DELETE ON `Question`
FOR EACH ROW
	BEGIN
		DECLARE ID_Q TINYINT;
		SELECT COUNT(EX.QuestionID) INTO ID_Q FROM `ExamQuestion` EX WHERE EX.QuestionID = OLD.QuestionID;
		IF (ID_Q =0) THEN
		SIGNAL SQLSTATE '12345'
		SET MESSAGE_TEXT = 'KHÔNG THỂ XÓA';
		END IF ;
END $$
DELIMITER ;
 DELETE FROM `Question` Q WHERE QuestionID = 877;

SELECT COUNT(EX.QuestionID) FROM `ExamQuestion` EX WHERE EX.QuestionID =876;